config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home' => 'pages#home'
  
  resources :recipes do
    resources :comments, only: [:create]
  end
  resources :chefs, :ingredients, :messages

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy' 

  mount ActionCable.server => '/cable'
  get '/chat' => 'chatrooms#show'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: {minimum: 5, maximum: 500}
    validates :chef_id, presence: true
    belongs_to :chef
    default_scope -> { order(updated_at: :desc)}
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients
    has_many :comments , dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, only: [:show,:edit, :update]
    before_action :require_user, except:[:index, :show]
    before_action :require_same_user, only: [:edit, :update, :delete]
    def index
        @recipes = Recipe.paginate(page: params[:page], per_page: 5)
    end

    def show
        @comment = Comment.new
        @comments = @recipe.comments.paginate(page: params[:page], 
                                                    per_page: 5)
      end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.chef = current_chef
        if @recipe.save
            flash[:success] = 'Recipe was created succesfully'
            redirect_to recipe_path(@recipe)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @recipe.update(recipe_params)
            flash[:success] = 'Recipe was updated'
            redirect_to recipe_path(@recipe)
        else
            render 'edit'
        end
    end
    
    def destroy
        @recipe = Recipe.find(params[:id])
        if @recipe.destroy
            flash[:success] = 'Recipe deleted succesfully'
            redirect_to recipes_path
        else
        end
    end

    private
        def set_recipe 
            @recipe = Recipe.find(params[:id])
        end

        def recipe_params
            params.require(:recipe).permit(:name, :description, ingredient_ids: [])
        end

        def require_same_user
            if current_chef != @recipe.chef && !current_chef.admin?
            flash[:danger] = 'Permission Denied'
            redirect_to recipes_path
        end    
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
    <div class='row'>
        <div class='col-md-2'>
			<section class='chef_info center'>
				<%= link_to gravatar_for(recipe.chef, size: 120), chef_path(recipe.chef) %>
			</section>
        </div>
	<div class='col-md-8 well'>
		<h4>  <%= link_to recipe.name, recipe_path(recipe) %>  </h4>
		<p> <%= truncate(recipe.description, length: 150) %> </p>
					<% if recipe.ingredients.any? %> 
						<p>Ingredients:&ensp;<%= render recipe.ingredients%> </p>
						<%# Rails magic for rendering the _ingredient partial %>
					<% end %>
				</ul>
		<p> <span class='quiet'> <small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%= link_to recipe.chef.name.capitalize, chef_path(recipe.chef) %> 
		| <%= pluralize(recipe.comments.count, 'Comment') %> </small></span> </p>
		    <% if is_logged_in && current_chef == recipe.chef || current_chef.try(:admin) %>   
            <%= link_to 'Edit', edit_recipe_path(recipe), class: 'btn btn-xs btn-warning'%>
            <%= link_to 'Delete', recipe_path(recipe), method: :delete, data: {confirm: 'Are you sure you want to delete?'}, class: 'btn btn-xs btn-danger' %>
        	<% end %>
	</div>
	</div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: 'Modify the recipe'%>
<%= render'shared/form'%>

app/views/recipes/index.html.erb
<%= render'shared/page_title', title: 'Listing all recipes'%>
<div align='center'>
    <%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: 'create a new recipe'%>
<%= render 'shared/form'%>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class='well col-md-8 col-md-offset-2'>
    <h4 class='center description'> <strong>Steps:  </strong></h4>
    <hr />
    <%= simple_format(@recipe.description) %>
    <% if @recipe.ingredients.any? %> 
        <p>Ingredients:&ensp;<%= render @recipe.ingredients%> </p>
        <%# Rails magic for rendering the _ingredient partial %>
	<% end %>
    <hr />
    <div class='pull-right'> 
        <p class='center'> 
            <em> Created by:</em> 
        </p>
    <p class='center'> 
        <%= link_to gravatar_for(@recipe.chef, size:60) , chef_path(@recipe.chef) %>
    </p>
    <p class='center'>
        <small> <%= @recipe.chef.name.capitalize %> </small>
        <div class='pull-right'> <%=time_ago_in_words(@recipe.created_at)%> ago </div>
    </p> 
    </div>
    <div class='recipe-actions'>
        <% if is_logged_in && current_chef == @recipe.chef || current_chef.try(:admin)%>   
            <%= link_to 'Edit', edit_recipe_path(@recipe), class: 'btn btn-xs btn-warning'%>
            <%= link_to 'Delete', recipe_path(@recipe), method: :delete, data: {confirm: 'Are you sure you want to delete?'}, class: 'btn btn-xs btn-danger' %>
        <% end %>
        <%= link_to 'Home', recipes_path, class: 'btn btn-xs btn-primary'%>
    </div>
</div>

<% if is_logged_in %>
    <div class='row'>
        <div class='col-md-8 col-md-offset-2'>
        <h3>Comments: </h3>
        <hr />    
            <%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |r| %>
                <div class='form-group'>
                    <div class='control-label col-md-2 pull-left'>
                        <%= r.label :description %>
                    </div>
                    <div class='col-md-8'>
                        <%= r.text_area :description, rows: 6, class: 'form-control', placeholder: 'Enter comment here'%>
                    </div>
                </div>
                    <br>
                <div class='form-group'>
                    <div class='col-md-offset-2 col-md-10'>
                        <%= r.submit 'Post comment', class: 'btn btn-primary btn-lg btn-xlarge'%>
                    </div>
                </div>
            <% end %>
            <hr>
        </div>
    </div>
<% end %>

<% if @recipe.comments != 0 %>
    <div class='row'>
        <div class='col-md-8 col-md-offset-2'>
            <h3>Prior Comments:</h3>
            <div id="messages">
                <%= render partial: 'comments/comments', object: @comment %>
            </div>
        </div>
    </div>
<% else %>
    <div class='row'>
        <div class='col-md-8 col-md-offset-2'>
            <h3>No Comments</h3>
        </div>
    </div>
<% end  %>