config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home' => 'pages#home'
  
  resources :recipes do
    resources :comments, only: [:create]
  end
  resources :chefs, :ingredients, :messages

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy' 

  mount ActionCable.server => '/cable'
  get '/chat' => 'chatrooms#show'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
    default_scope -> { order(name: :asc)}
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    before_action :require_admin, except: [:show, :index]
    def index
        @ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
    end

    def show
        @ingredient = Ingredient.find(params[:id])
        @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
    end

    def new
        @ingredient = Ingredient.new
    end

    def create
        @ingredient = Ingredient.new(ingredient_params)
        if @ingredient.save
            flash[:success] = 'Ingredient successfully added'
            redirect_to ingredients_path
        else
            render 'new'
        end
    end
    
    def edit
        @ingredient = Ingredient.find(params[:id])
    end

    def update
        @ingredient = Ingredient.find(params[:id])
        if @ingredient.update(ingredient_params)
            flash[:success] = 'Ingredient updated'
            redirect_to ingredients_path
        else
            render 'edit'
        end
    end

    def destroy
        @ingredient = Ingredient.find(params[:id])
        @ingredient.destroy
    end

    private
        def ingredient_params
            params.require(:ingredient).permit(:name)
        end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_ingredient.html.erb
<span class='badge ingredient-badge'> <%= link_to ingredient.name, ingredient_path(ingredient) %>  </span>

app/views/ingredients/_ingredient_form.html.erb
    <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |i| %>
            <div class='form-group'>
                <div class='control-label col-md-2 pull-left'>
                    <%= i.label :name %>
                </div>
                <div class='col-md-8'>
                    <%= i.text_field :name, class: 'form-control', placeholder: 'Ingredient', autofocus: true%>
                </div>
            </div>


            <div class='form-group'>
                <div class='col-md-offset-2 col-md-10'>
                    <%= i.submit class: 'btn btn-primary btn-lg btn-xlarge'%>
                </div>
            </div>
        <% end %>

        <div class='col-md-4 col-md-offset-4 colormatch'>
            [ <%= link_to 'Cancel', recipes_path %> ]
        </div>

app/views/ingredients/edit.html.erb
<%= render 'shared/page_title', title: 'Edit ingredient'%>
<%= render 'shared/errors', obj: @ingredient%>
<%= render 'ingredient_form'%>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: 'showing all ingredients'%>

<div align='center'>
    <%= will_paginate %>
</div>

<div align='center'>
    <% @ingredients.each do |ingredient| %>
        <ul class='listing'> 
            <div class='row'>
                <div class='well col-md-4 col-md-offset-4'>
                    <li class='chef-title'> <%= link_to ingredient.name.capitalize, ingredient_path(ingredient) %> </li>
                    <li> <small> <%= pluralize(ingredient.recipes.count, 'recipe') if ingredient.recipes %> </small> </li>
                <% if is_logged_in && current_chef.try(:admin) %>
                    <li> <%= link_to 'Edit this ingredient', ingredient_path(ingredient) %> </li>
                <% end %>
                </div>
            </div>
        </ul>
    <% end %>
</div>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: 'Add a new ingredient'%>
<%= render 'shared/errors', obj: @ingredient%>
<%= render 'ingredient_form'%>

app/views/ingredients/show.html.erb
<%=  render 'shared/page_title', title: "Recipes with #{@ingredient.name}"%>
<div class='row'>
    <div class='col-md-4 col-md-offset-4 center'>
    </div>
    <div class='pull-right'>
    <% if is_logged_in && current_chef.try(:admin)%>
        <%= link_to 'Edit Ingredient', edit_ingredient_path(@ingredient) %>
        <%= link_to 'Delete Ingredient', ingredient_path(@ingredient), method: :delete, data: {confirm: 'Are you sure'}, class: 'btn btn-xs btn-danger' %>
    <% end %>
    </div>
</div>

<% if @ingredient.recipes.count > 0%>
<h4 align='center'> </h4>
<div align='center'>

<%= will_paginate @ingredient_recipes %>

</div>
<%=render 'recipes/recipe', obj: @ingredient.recipes%>
<% else %>
<h4 align='center'> No recipes yet</h4>
<% end %>