config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home' => 'pages#home'
  
  resources :recipes do
    resources :comments, only: [:create]
  end
  resources :chefs, :ingredients, :messages

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy' 

  mount ActionCable.server => '/cable'
  get '/chat' => 'chatrooms#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
    before_save {self.email = self.email.downcase}
    validates :name, presence: true, length: {minimum: 2, maximum: 30}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255},
                format: {with: VALID_EMAIL_REGEX},
                uniqueness: { case_sensitive: false }
    has_many :recipes , dependent: :destroy
    has_secure_password
    validates :password, presence: true, length: {minimum: 5}, allow_nil: true
    has_many :comments , dependent: :destroy
    has_many :messages, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :description, presence: true, length: {minimum: 2, maximum: 140}
    belongs_to :chef
    belongs_to :recipe
    validates :chef_id, presence: true
    validates :recipe_id, presence: true
    default_scope -> { order(updated_at: :desc)}

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
    default_scope -> { order(name: :asc)}
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :chef
    validates :content, presence: true
    validates :chef_id, presence: true

    def self.most_recent
        #orders the result set by created at and only fetches the last 20
        order(:created_at).last(20)
    end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: {minimum: 5, maximum: 500}
    validates :chef_id, presence: true
    belongs_to :chef
    default_scope -> { order(updated_at: :desc)}
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients
    has_many :comments , dependent: :destroy
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    belongs_to :ingredient
    belongs_to :recipe
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
    before_action :set_chef, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def index
        @chefs = Chef.paginate(page:params[:page], per_page: 5)
    end

    def show
        @chef_recipes = @chef.recipes.paginate(page:params[:page], per_page: 4)
    end
    
    def new
        @chef = Chef.new
    end

    def create
        @chef = Chef.new(chef_params)
        if @chef.save
            session[:chef_id] = @chef.id
            cookies.signed[:chef_id] = @chef.id
            flash[:success] = "Welcome #{@chef.name} to MYRECIPES App"
            redirect_to chef_path(@chef)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @chef.update(chef_params)
            flash[:success] = 'Chef profile was updated'
            redirect_to @chef
        else
            render 'edit'
        end
    end

    def destroy 
       #if current chef is deleting account have to log out after deleting chef
       if(current_chef == @chef) 
        session[:chef_id] = nil
       end
        @chef.destroy
        flash[:success] = 'Profile was successfully deleted'
        redirect_to chefs_path
    end

    private
        def chef_params
            params.require(:chef).permit(:name, :email, :password, :password_confirmation)
        end

        def set_chef
            @chef = Chef.find(params[:id])
        end

        def require_same_user
            if  current_chef != @chef && !current_chef.admin
                flash[:danger] = 'Permission Denied'
                redirect_to chef_path(current_chef)
            end
        end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :require_user
    def create
        @recipe = Recipe.find(params[:recipe_id])
        @comment = @recipe.comments.build(comment_params)
        @comment.chef = current_chef
        if @comment.save
            ActionCable.server.broadcast "comments", render(partial: 'comments/comment', object: @comment)
            #flash[:success] = 'Comment posted'
            #redirect_to recipe_path(@recipe)
        else
            flash[:danger] = 'Comment was not created'        
            redirect_back(fallback_location: recipe_path(@recipe))
        end
    end

    private 
        def comment_params
        params.require(:comment).permit(:description)
         end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to recipes_path if is_logged_in
        @recipes = Recipe.all.limit(3)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, only: [:show,:edit, :update]
    before_action :require_user, except:[:index, :show]
    before_action :require_same_user, only: [:edit, :update, :delete]
    def index
        @recipes = Recipe.paginate(page: params[:page], per_page: 5)
    end

    def show
        @comment = Comment.new
        @comments = @recipe.comments.paginate(page: params[:page], 
                                                    per_page: 5)
      end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.chef = current_chef
        if @recipe.save
            flash[:success] = 'Recipe was created succesfully'
            redirect_to recipe_path(@recipe)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @recipe.update(recipe_params)
            flash[:success] = 'Recipe was updated'
            redirect_to recipe_path(@recipe)
        else
            render 'edit'
        end
    end
    
    def destroy
        @recipe = Recipe.find(params[:id])
        if @recipe.destroy
            flash[:success] = 'Recipe deleted succesfully'
            redirect_to recipes_path
        else
        end
    end

    private
        def set_recipe 
            @recipe = Recipe.find(params[:id])
        end

        def recipe_params
            params.require(:recipe).permit(:name, :description, ingredient_ids: [])
        end

        def require_same_user
            if current_chef != @recipe.chef && !current_chef.admin?
            flash[:danger] = 'Permission Denied'
            redirect_to recipes_path
        end    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "img-circle")
    end

end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
    <strong>Built by <a href="https://hoongandre.ca">Slickhoss Development</a> </strong>
    </small>
    <nav>
        <ul>
            <li> <%= link_to 'About', '#'  %> </li> 
        </ul> 
    </nav>
</footer>

app/views/layouts/_messages.html.erb
    <div class='row'>
        <div class='col-md-10 col-md-offset-1'>
            <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name %>">
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                                <%= msg %>

            </div>
            <% end %>
        </div>
    </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">MY RECIPE</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Chefs', chefs_path %> </li>
        <li><%= link_to 'Recipes', recipes_path %> </li>
        <% if is_logged_in %>
        <li><%= link_to 'Chef Chat', chat_path %> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'All Recipes', recipes_path %> </li>
            <li><%= link_to 'Add Recipe', new_recipe_path %> </li>
          </ul>
        </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">All Ingredients<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'All Ingredients', ingredients_path %> </li>
            <% Ingredient.all.each do |i| %>
              <li> <%= link_to i.name.capitalize, ingredient_path(i) %> </li>
            <% end %>

            <% if is_logged_in && current_chef.try(:admin) %>
              <li role='seperator' class='divider'> </li>
              <li><%= link_to 'Add Ingredient', new_ingredient_path %> </li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if is_logged_in %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.name.capitalize %>'s Profile <%= 'Admin' if current_chef.admin%> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'View Profile', chef_path(current_chef) %></li>
              <li><%= link_to 'Edit Profile', edit_chef_path(current_chef) %> </li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Logout', logout_path, method: :delete%></li>
            </ul>
          </li>
        <% else %>
          <li> <%= link_to 'Login', login_path %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyrecipesRailsapp</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages'%>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
  <%= render 'layouts/footer'%>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
<h1>Welcome to my recipes</h1>
<h2>The best recipe sharing app built using ruby on rails</h2>
<p> <%= link_to 'Sign Up', new_chef_path, class: 'btn btn-primary btn-xlarge' %></p>
</div>

<div class="row">
    <% @recipes.each do |r| %>
        <div class="col-lg-4">
    <h2><%= r.name %> </h2>
    <p class='text-danger'></p>
    <p><%= r.description %> </p>
    <p><%= link_to 'View More', recipe_path(r) %>  </p>
    </div>
    <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class='row'>
    <div class='col-md-8 col-md-offset-2'>
        <div class='panel panel-danger'>
            <div class='panel-heading'>    
                <h2 class='panel-title'> 
                    <%= pluralize(obj.errors.count, 'error')%>
                    prohibited this <%= obj.class %> from being saved:
                </h2>
                <div class='panel-body'>            
                    <ul>
                        <% obj.errors.full_messages.each do |msg| %>
                            <li> <%= msg %> </li>
                        <% end %>
                    <ul>  
                </div>
            </div>

        </div>
    </div>
</div>
<% end %>

app/views/shared/_form.html.erb
<%= render 'shared/errors', obj: @recipe%>

<div class='row'>
    <div class='col-md-12'>    
        <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |r| %>
            <div class='form-group'>
                <div class='control-label col-md-2 pull-left'>
                    <%= r.label :name %>
                </div>
                <div class='col-md-8'>
                    <%= r.text_field :name, class: 'form-control', placeholder: 'Name of recipe', autofocus: true%>
                </div>
            </div>

            <div class='form-group'>
                <div class='control-label col-md-2 pull-left'>
                    <%= r.label :description %>
                </div>
                <div class='col-md-8'>
                    <%= r.text_area :description, rows: 10, class: 'form-control', placeholder: 'Steps'%>
                </div>
            </div>

            <div class='form-group'>
                <div class='row'>
                    <div class='col-md-offset-2 col-md-8'>
                        <%= r.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |i| %>
                            <%= i.label(class: 'checkbox-inline input_checkbox') {i.check_box(class: 'checkbox') + i.text}%>
                        <% end %>
                    </div>
            </div>
                <br>
            <div class='form-group'>
                <div class='col-md-offset-2 col-md-10'>
                    <%= r.submit class: 'btn btn-primary btn-lg btn-xlarge'%>
                </div>
            </div>
        <% end %>

        <div class='col-md-4 col-md-offset-4 colormatch'>
            [ <%= link_to 'Cancel', recipes_path %> ]
        </div>
    </div>
</div>

app/views/shared/_page_title.html.erb
<h1 align='center'><%= title.capitalize %> </h1>
<hr>